name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 18.7.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.7.0'
          check-latest: false
      - run: npm install
      - run: npm run build --prefix client
